### ISSUE TITLE
myStrom Wifi Switch photovoltaic

### ISSUE THREAD

**Issue by Pythonaire** [home-assistant-ecosystem/python-mystrom#41]
the switch has the ability be used for photovoltaic unit. In this case, i want to read the earned Watt. I just find power consumption.
How can i read the power delivery value?

**Comment by fabaff** [comment]
I don't know as the [documentation](https://api.mystrom.ch/#fbb2c698-e37a-4584-9324-3f8b2f615fe2) doesn't mention this. It's probably only available in the myStrom App.

**Comment by Pythonaire** [comment]
The standard HAP interface don’t have characteristics for power production, just consumption. The mystrom switch is HAP certified, so I hope they have a UUID (service and characteristic) for power production - should have this. Typically the existing UUIDs will be offered at the first connect to the HAP interface. Are you able to trace the connection? It would be very helpfull

many thx

**Comment by dbrgn** [comment]
If you call the [`/report` endpoint](https://api.mystrom.ch/#fbb2c698-e37a-4584-9324-3f8b2f615fe2), you get the following output:

```json
{
    "Ws": 26.43,
    "boot_id": "85A81EF3",
    "energy_since_boot": 278809314.67,
    "power": 27.29,
    "relay": true,
    "temperature": 20.58,
    "time_since_boot": 2612678
}
```

-> `energy_since_boot` should be what you need.

If you use HomeAssistant, you can also use an integration instead to calculate energy production (or consumption).

```yaml
sensor:  - platform: integration
    source: sensor.mystrom_solar_leistung
    unique_id: balkonsolar_production
    name: "myStrom Solar Production"
    unit_prefix: k
    round: 3
```

(Source sensor must be adjusted of course.)
